//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosReserva
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ReservasAereasEntities1 : DbContext
    {
        public ReservasAereasEntities1()
            : base("name=ReservasAereasEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DatosReserva> DatosReserva { get; set; }
        public virtual DbSet<PrecioTP> PrecioTP { get; set; }
    
        public virtual ObjectResult<SP_TraerData_Result> SP_TraerData(string aeropuertoDeOrigen, string aeropuertoDeLlegada, string aerolinea)
        {
            var aeropuertoDeOrigenParameter = aeropuertoDeOrigen != null ?
                new ObjectParameter("AeropuertoDeOrigen", aeropuertoDeOrigen) :
                new ObjectParameter("AeropuertoDeOrigen", typeof(string));
    
            var aeropuertoDeLlegadaParameter = aeropuertoDeLlegada != null ?
                new ObjectParameter("AeropuertoDeLlegada", aeropuertoDeLlegada) :
                new ObjectParameter("AeropuertoDeLlegada", typeof(string));
    
            var aerolineaParameter = aerolinea != null ?
                new ObjectParameter("Aerolinea", aerolinea) :
                new ObjectParameter("Aerolinea", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TraerData_Result>("SP_TraerData", aeropuertoDeOrigenParameter, aeropuertoDeLlegadaParameter, aerolineaParameter);
        }
    }
}
