//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosReserva
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosReserva
    {
        public int IdReserva { get; set; }
        public string AeropuertoDeOrigen { get; set; }
        public string HoraSalida { get; set; }
        public string AeropuertoDeLlegada { get; set; }
        public string Aerolinea { get; set; }
        public Nullable<int> NumeroVuelo { get; set; }
        public Nullable<int> TipoPasajero { get; set; }
        public string HoraLlegada { get; set; }
        public Nullable<System.DateTime> FechaViaje { get; set; }
    }
}
